### ISSUE TITLE
Adding Self-Sovereign Bill of Rights

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/self-sovereign-identity#5]
@boscolochris, could you make a pull request and add your Self-Sovereign Bill of Rights as a new file to this repo, and edit the README.md to link it in along with any reference to your original blog post.

**Comment by cboscolo** [comment]
Done. #7 
Also, just an FYI "@boscolochris" is my twitter handle. @cboscolo is my github username.
All these digital identities... what a pain!
